POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "First class tests",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
    "likes": 87,
    "user": "5fd51974a52aa3193008df38"
}
